spring:
  profiles:
    active: usage_message
  rabbitmq:
    password: ${rabbitmq.password:guest}

  cloud:
    stream:
      bindings:
        user_management:
          destination: userChannel

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 60000
